version: '2.27.0'  # Docker Compose的版本
services: # 定义服务
  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos
    hostname: nacos
    networks:
      - dev_env
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    volumes:
      - nacos_data:/home/nacos/data
    environment:
      - MODE=standalone
    depends_on:
      mysql:
        condition: service_healthy
    restart: always

  mysql: # 服务名称
    image: mysql:8  # 使用的镜像
    container_name: mysql  # 容器名称
    hostname: mysql  # 主机名
    networks: # 网络
      - dev_env  # 使用的网络名称
    ports: # 端口映射
      - "3307:3306"  # 宿主机端口:容器端口
    environment: # 环境变量
      MYSQL_ROOT_PASSWORD: 114514  # MySQL root用户的密码
      # MYSQL_ROOT_HOST: "%"  # 允许root用户远程连接(可能需要先删除已有数据卷)
      MYSQL_DATABASE: mall  # 创建的数据库名
      MYSQL_SERVICE_USER: nacos
      MYSQL_SERVICE_PASSWORD: nacos
      MYSQL_CHARACTER_SET_SERVER: utf8mb4  # 服务器字符集
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci  # 服务器排序规则
      MYSQL_MAX_CONNECTIONS: 1000  # 最大连接数
    volumes: # 卷
      - mysql_data:/var/lib/mysql  # 宿主机卷路径:容器内卷路径
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 10

  redis: # 服务名称
    image: redis:latest  # 使用的镜像
    container_name: redis  # 容器名称
    hostname: redis  # 主机名
    networks: # 网络
      - dev_env  # 使用的网络名称
    ports: # 端口映射
      - "6379:6379"  # 宿主机端口:容器端口
    environment:
      - REDIS_PASSWORD=114514  # Redis密码
    command: redis-server --requirepass 114514
    volumes: # 卷
      - redis_data:/data  # 宿主机卷路径:容器内卷路径

  rabbitmq: # 服务名称
    build:
      context: .
      dockerfile: Dockerfile.rabbitmq  # 使用新的Dockerfile
    container_name: rabbitmq  # 容器名称
    hostname: rabbitmq  # 主机名
    networks: # 网络
      - dev_env  # 使用的网络名称
    ports: # 端口映射
      - "5672:5672"  # 宿主机端口:容器端口
      - "15672:15672"  # 宿主机端口:容器端口
    environment: # 环境变量
      RABBITMQ_DEFAULT_USER: root  # RabbitMQ默认用户名
      RABBITMQ_DEFAULT_PASS: 114514  # RabbitMQ默认密码
    volumes: # 卷
      - rabbitmq_data:/var/lib/rabbitmq  # 宿主机卷路径:容器内卷路径

  nginx: # 服务名称
    image: nginx:latest  # 使用的镜像
    container_name: nginx  # 容器名称
    hostname: nginx  # 主机名
    networks: # 网络
      - dev_env  # 使用的网络名称
    ports: # 端口映射
      - "80:80"  # 宿主机端口:容器端口
    volumes: # 卷
      - ./nginx.conf:/etc/nginx/nginx.conf  # 宿主机卷路径:容器内卷路径
      - nginx_data:/usr/share/nginx/html  # 宿主机卷路径:容器内卷路径

networks: # 定义网络
  dev_env:  # 网络名称

volumes: # 定义卷
  nacos_data:  # 卷名称
  mysql_data:  # 卷名称
  redis_data:  # 卷名称
  rabbitmq_data:  # 卷名称
  nginx_data:  # 卷名称