my:
  db: localhost
server:
  port: 8060

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${my.db}:3306/mall?useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: 114514
  application:
    name: order-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  redis:
    host: localhost
    port: 6379
    password: 114514

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: g_status
      logic-delete-value: 1
      logic-not-delete-value: 0

management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

feign:
  okhttp:
    enabled: true

logging:
  level:
    com.mole: debug

