my:
  nacos:
    server: localhost
  db: localhost
  auth:
    excludePaths:
      - /login
      - /register
      - /**
server:
  port: 8080

spring:
  application:
    name: gateway-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${my.db}:3306/mall?useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true # 数据库连接URL
    username: root
    password: 114514
  redis:
    host: localhost # Redis服务器地址
    port: 6379 # Redis服务器端口
    password: 114514 # Redis密码
  main:
    web-application-type: reactive
  cloud:
    nacos:
      server-addr: ${my.nacos.server}:8848

    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/login,/register,/change-password,/logout,/admin/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/members/**,/admins/**
        - id: marketing-service
          uri: lb://marketing-service
          predicates:
            - Path=/coupons/**,/couponHistories/**,/flashPromotions/**,/flashpromotionproductrelation/**,/flash-promotion-sessions/**,/home-advertises/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**,/returnApply/**,/returnReasons/**,/orderSetting/**,/operateHistories/**,/CompanyAddress/**,/OrderItem/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/brand/**,/product/**,/productCategory/**

management: # 管理端配置
  endpoint:
    health:
      show-details: always # 健康检查显示详情
    httptrace:
      enabled: true # 启用HTTP跟踪
    shutdown:
      enabled: true # 启用关闭端点
  endpoints:
    web:
      exposure:
        include: '*' # 暴露所有端点